# Vi keybindings
bindkey -v

# Antigen
source $HOME/antigen.zsh
antigen use oh-my-zsh

# Oh-My-Zsh plugins
antigen bundle dirhistory
antigen bundle history
antigen bundle last-working-dir
antigen bundle sbt
antigen bundle scala
antigen bundle screen
antigen bundle vi-mode

# Zsh-Users plugins
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting

# Powerline
source /usr/share/powerline/bindings/zsh/powerline.zsh

# ROS
source /opt/ros/kinetic/setup.zsh

# Catkin Workspace
local catkin_setup=$HOME/catkin_ws/devel/setup.zsh
if [ -f "$catkin_setup" ]; then
    source "$catkin_setup"
fi

# Restart container
alias stop='killall sleep'

# Ardupilot SITL
export PATH=$PATH:$HOME/jsbsim/src
export PATH=$PATH:$HOME/ardupilot/Tools/autotest
export PATH=/usr/lib/ccache:$PATH
export MAP_SERVICE=OpenStreetMap

# Aliases
alias ls='ls --color=auto'

if [ "$GCS_CLIENT_MODE" ]; then
    # Host roscore
    export ROS_MASTER_URI="http://$(/sbin/ip route | awk '/default/ { print $3 }'):11311/"
    export ROS_IP="$(/sbin/ip addr show dev eth0 | awk '/inet/ { print $2 }' | cut -d/ -f1)"
fi

# Turtlebot 3 Model
export TURTLEBOT3_MODEL=waffle_pi

# For VirtualBox
export TERM=xterm-256color
