# Vi keybindings
bindkey -v

# Antigen
source /home/ros/antigen.zsh
antigen use oh-my-zsh

# Oh-My-Zsh plugins
antigen bundle dirhistory
antigen bundle history
antigen bundle last-working-dir
antigen bundle sbt
antigen bundle scala
antigen bundle screen
antigen bundle vi-mode

# Zsh-Users plugins
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting

# Powerline
source /usr/share/powerline/bindings/zsh/powerline.zsh

# ROS
source /opt/ros/kinetic/setup.zsh

# Catkin Workspace
local catkin_setup=/home/ros/catkin_ws/devel/setup.zsh
if [ -x "$catkin_setup" ]; then
    source "$catkin_setup"
fi

# Restart container
alias stop='killall roscore'

# Ardupilot SITL
export PATH=$PATH:$HOME/jsbsim/src
export PATH=$PATH:$HOME/ardupilot/Tools/autotest
export PATH=/usr/lib/ccache:$PATH
